/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-08-01 06:14:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.DaoLoaiSanPham;
import model.ModelLoaiSanPham;
import model.ModelChiTietSanPham;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;

public final class addproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.DaoLoaiSanPham");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.ModelLoaiSanPham");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("model.ModelChiTietSanPham");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(">\r\n");
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thông Tin Sản Phẩm</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	ModelChiTietSanPham obj = (ModelChiTietSanPham) request.getAttribute("editItemInfo");
	if (obj == null) {
		obj = new ModelChiTietSanPham();
	}
	SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
	String importDate = formatter.format(obj.getNgayNhap());
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h2>THÔNG TIN SẢN PHẨM:</h2>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"./modifyProductAction\" method=\"post\">\r\n");
      out.write("		<table style=\"background-color: yellow;\">\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Loại sản phẩm</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<select name=\"productType\">\r\n");
      out.write("							");

							List loatSanPhamList = (List) request.getAttribute("loatSanPhamList");
							try {
								ModelLoaiSanPham lsp;
								for (Object objLsp : loatSanPhamList) {
										lsp = (ModelLoaiSanPham)objLsp;
							
      out.write("\r\n");
      out.write("									<option ");
      out.print(((lsp.getLoaiSPCode() == obj.getLoaiSPCode())?
													"selected=\"selected\"":""));
      out.write("\r\n");
      out.write("											value=\"");
      out.print(lsp.getLoaiSPCode());
      out.write('"');
      out.write('>');
      out.print(lsp.getTenLoaiSP());
      out.write("<option>\r\n");
      out.write("\r\n");
      out.write("							");

								}
							} catch (Exception ex) {
								ex.printStackTrace();
							}
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						</select>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Tên Sản Phẩm</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"productName\"\r\n");
      out.write("						value=\"");
      out.print(obj.getTenSP());
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Ngày Nhập</td>\r\n");
      out.write("					<td><input type=\"date\" name=\"importDate\" value=");
      out.print(importDate);
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Giá Nhập</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"importPrice\"\r\n");
      out.write("						value=");
      out.print(obj.getGiaNhap());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Giá Bán</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"exportPrice\"\r\n");
      out.write("						value=");
      out.print(obj.getGiaBan());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Số Lượng</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"aMount\"\r\n");
      out.write("						value=");
      out.print(obj.getSoLuong());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Giảm Giá</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Discount\"\r\n");
      out.write("						value=");
      out.print(obj.getGiamGia());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Mã Nhà Cung Cấp</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"supplierCode\"\r\n");
      out.write("						value=");
      out.print(obj.getNhaCungCapCode());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"hidden\" name=\"updateItemId\"\r\n");
      out.write("						value=");
      out.print(obj.getSanPhamCode());
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<button type=\"submit\">Hoàn Thành</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
