/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-08-01 16:00:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.IOException;
import java.util.List;
import model.ModelChiTietSanPham;
import dao.DaoChiTietSanPham;
import dao.DaoKhachHang;
import model.ModelKhachHang;
import dao.DaoDanhMucSanPham;
import model.ModelDanhMucSanPham;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/i18ntag.tld", Long.valueOf(1626349467742L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.DaoKhachHang");
    _jspx_imports_classes.add("dao.DaoChiTietSanPham");
    _jspx_imports_classes.add("model.ModelDanhMucSanPham");
    _jspx_imports_classes.add("model.ModelKhachHang");
    _jspx_imports_classes.add("dao.DaoDanhMucSanPham");
    _jspx_imports_classes.add("model.ModelChiTietSanPham");
    _jspx_imports_classes.add("java.io.IOException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.ArrayList spList = null;
      spList = (java.util.ArrayList) _jspx_page_context.getAttribute("spList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (spList == null){
        spList = new java.util.ArrayList();
        _jspx_page_context.setAttribute("spList", spList, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.ArrayList spListdm = null;
      spListdm = (java.util.ArrayList) _jspx_page_context.getAttribute("spListdm", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (spListdm == null){
        spListdm = new java.util.ArrayList();
        _jspx_page_context.setAttribute("spListdm", spListdm, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./bootstrap/bootstrap.min.css\">\r\n");
      out.write("<script src=\"./bootstrap/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"./bootstrap/popper.min.js\"></script>\r\n");
      out.write("<script src=\"./bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	var masID_ = \"masLayer_\";\r\n");
      out.write("	$(document).ready(function() {			\r\n");
      out.write("			\r\n");
      out.write("		document.addEventListener(\"keydown\", (e) => {\r\n");
      out.write("		    console.log(\"Escape key is pressed say hi \\n\");\r\n");
      out.write("		    $(\"#update_pop-up\").fadeOut(500);\r\n");
      out.write("			var layer = document.getElementById(masID_);\r\n");
      out.write("			document.body.removeChild(layer);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#close_button\").click(function() {\r\n");
      out.write("			$(\"#update_pop-up\").fadeOut(500);\r\n");
      out.write("			var layer = document.getElementById(masID_);\r\n");
      out.write("			document.body.removeChild(layer);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		$(\"#update_pơpup\").click(function() {\r\n");
      out.write("			$(\"#update_pop-up\").animate({left: '630px', top: '100px'});\r\n");
      out.write("			$(\"#update_pop-up\").slideDown(500);\r\n");
      out.write("			$(\"#update_pop-up\").css(\"z-index\", \"1000\");\r\n");
      out.write("			\r\n");
      out.write("			var layer = document.createElement(\"div\");\r\n");
      out.write("			layer.setAttribute(\"id\", masID_);\r\n");
      out.write("			$(layer).css(\"position\", \"absolute\");\r\n");
      out.write("			$(layer).animate({left: '0px', top: '0px'});\r\n");
      out.write("			$(layer).css(\"width\", \"100%\");\r\n");
      out.write("			$(layer).css(\"height\", \"100%\");\r\n");
      out.write("			$(layer).css(\"background-color\", \"gray\");\r\n");
      out.write("			$(layer).css(\"z-index\", \"500\");\r\n");
      out.write("			$(layer).css(\"opacity\", \"0.25\");\r\n");
      out.write("			document.body.append(layer);\r\n");
      out.write("		});		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container text-uppercase\" style=\"margin: 10px 0px\">Lá»p\r\n");
      out.write("		Java18</div>\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-dark navbar-dark fixed-top\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"#\">Logo</a>\r\n");
      out.write("		<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("			data-toggle=\"collapse\" data-target=\"#navbMenu\" aria-expanded=\"true\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbMenu\">\r\n");
      out.write("			<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">");
      if (_jspx_meth_i18n_005fi18ntag_005f0(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle \" id=\"\" data-toggle=\"dropdown\">");
      if (_jspx_meth_i18n_005fi18ntag_005f1(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("					<div class=\"dropdown-menu\">\r\n");
      out.write("						<a href=\"./daoDanhMucAction?DanhMucSP=dm\" class=\"dropdown-item\">Danh\r\n");
      out.write("							muc SP</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">");
      if (_jspx_meth_i18n_005fi18ntag_005f2(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" id=\"\" data-toggle=\"dropdown\">");
      if (_jspx_meth_i18n_005fi18ntag_005f3(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("					<div class=\"dropdown-menu\">\r\n");
      out.write("						<a href=\"#\" class=\"dropdown-item\">");
      if (_jspx_meth_i18n_005fi18ntag_005f4(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("						<a href=\"#\" class=\"dropdown-item\">");
      if (_jspx_meth_i18n_005fi18ntag_005f5(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("						<a href=\"#\" class=\"dropdown-item\">");
      if (_jspx_meth_i18n_005fi18ntag_005f6(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<form class=\"form-inline my-2 my-lg-0\" action=\"#\"\r\n");
      out.write("				style=\"margin-right: 15px;\">\r\n");
      out.write("				<input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("				<button class=\"btn btn-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("				<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle \" id=\"\" data-toggle=\"dropdown\">Languages</a>\r\n");
      out.write("						<div class=\"dropdown-menu\">\r\n");
      out.write("							<a href=\"./changeLanguage?Language=vi\" class=\"dropdown-item\">Vietnamese</a>\r\n");
      out.write("							<a href=\"./changeLanguage?Language=en\" class=\"dropdown-item\">English</a>\r\n");
      out.write("						</div></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\" style=\"border: 1px solid red; margin-top: 35px;\">\r\n");
      out.write("		<h1 class=\"text-uppercase\">\r\n");
      out.write("			");
      if (_jspx_meth_i18n_005fi18ntag_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			>>\r\n");
      out.write("			");
      if (_jspx_meth_i18n_005fi18ntag_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</h1>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-4 text-right\"\r\n");
      out.write("				style=\"background-color: lavenderblush;\">\r\n");
      out.write("				");
      if (_jspx_meth_i18n_005fi18ntag_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f10(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("								<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f11(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("								<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f12(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("								<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f13(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

							ModelDanhMucSanPham dmsp;
											for (Object objdm : spListdm) {
												dmsp = (ModelDanhMucSanPham) objdm;
							
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>");
      out.print(dmsp.getSanPhamCode());
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print(dmsp.getTenSP());
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print(dmsp.getGiaBan());
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print(dmsp.getGiamGia());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<!-- 								<td> -->\r\n");
      out.write("<!-- 									<form action=\"./modifyProductAction\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- 										<button type=\"submit\" class=\"btn btn-success btn-sm\"> -->\r\n");
      out.write("<!-- 											Edit</button> -->\r\n");
      out.write("<!-- 									</form> -->\r\n");
      out.write("<!-- 								</td> -->\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-8\" style=\"background-color: lavender;\">\r\n");
      out.write("\r\n");
      out.write("				<table\r\n");
      out.write("					class=\"table table-striped table-bordered table-hover table-sm\"\r\n");
      out.write("					style=\"margin-top: 30px;\">\r\n");
      out.write("					<caption class=\"text-uppercase\">\r\n");
      out.write("						");
      if (_jspx_meth_i18n_005fi18ntag_005f14(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<div style=\"float: right\">\r\n");
      out.write("\r\n");
      out.write("<!-- 							<form action=\"./addproduct.jsp\"> -->\r\n");
      out.write("							<form action=\"./modifyProductAction\">\r\n");
      out.write("								<input class=\"btn btn-primary btn-md\" type=\"submit\"\r\n");
      out.write("									value=\"");
      if (_jspx_meth_i18n_005fi18ntag_005f15(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("							</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-info btn-md\">\r\n");
      out.write("								");
      if (_jspx_meth_i18n_005fi18ntag_005f16(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</button>\r\n");
      out.write("							<button id=\"update_pơpup\" type=\"button\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("								");
      if (_jspx_meth_i18n_005fi18ntag_005f17(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</caption>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f18(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("							<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f19(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("							<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f20(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("							<th>");
      if (_jspx_meth_i18n_005fi18ntag_005f21(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						ModelChiTietSanPham sp;
						for (Object obj : spList) {
							sp = (ModelChiTietSanPham) obj;
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print(sp.getSanPhamCode());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(sp.getTenSP());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(sp.getTenLoaiSP());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(sp.getTenNhaCungCap());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("							<td>\r\n");
      out.write("\r\n");
      out.write("								<form action=\"./gioHangAction\" method=\"post\">\r\n");
      out.write("									<input type=\"hidden\" name=\"productID\" value=");
      out.print(sp.getSanPhamCode());
      out.write(">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("										Chon mua</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</td>\r\n");
      out.write("							\r\n");
      out.write("							<td>\r\n");
      out.write("								<form action=\"./modifyProductAction\">\r\n");
      out.write("									<input type=\"hidden\" name=\"productID\" value=");
      out.print(sp.getSanPhamCode());
      out.write(">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("										Edit</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</td>\r\n");
      out.write("\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"update_pop-up\" style=\"display: none; border: 1px solid blue; padding: 5px; width: 40%; min-width:640px;position: absolute; background-color: white;\">\r\n");
      out.write("				<div id=\"close_button\" style=\"position: absolute; with:20px;height: 20px;top: 3px;right: 8px;z-index: 1000; color : red; cursor: pointer; \">X</div>\r\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "productForm.jsp", out, false);
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\" style=\"border: 1px solid blue\">\r\n");
      out.write("		container-fluid</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f0 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f0);
    try {
      _jspx_th_i18n_005fi18ntag_005f0.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f0, null));
      _jspx_th_i18n_005fi18ntag_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f1 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f1);
    try {
      _jspx_th_i18n_005fi18ntag_005f1.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f1, null));
      _jspx_th_i18n_005fi18ntag_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f2 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f2);
    try {
      _jspx_th_i18n_005fi18ntag_005f2.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f2.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f2, null));
      _jspx_th_i18n_005fi18ntag_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f3 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f3);
    try {
      _jspx_th_i18n_005fi18ntag_005f3.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f3.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f3, null));
      _jspx_th_i18n_005fi18ntag_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f4 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f4);
    try {
      _jspx_th_i18n_005fi18ntag_005f4.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f4.setJspBody(new Helper( 4, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f4, null));
      _jspx_th_i18n_005fi18ntag_005f4.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f5 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f5);
    try {
      _jspx_th_i18n_005fi18ntag_005f5.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f5.setJspBody(new Helper( 5, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f5, null));
      _jspx_th_i18n_005fi18ntag_005f5.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f6 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f6);
    try {
      _jspx_th_i18n_005fi18ntag_005f6.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f6.setJspBody(new Helper( 6, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f6, null));
      _jspx_th_i18n_005fi18ntag_005f6.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f7 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f7);
    try {
      _jspx_th_i18n_005fi18ntag_005f7.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f7.setJspBody(new Helper( 7, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f7, null));
      _jspx_th_i18n_005fi18ntag_005f7.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f8 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f8);
    try {
      _jspx_th_i18n_005fi18ntag_005f8.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f8.setJspBody(new Helper( 8, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f8, null));
      _jspx_th_i18n_005fi18ntag_005f8.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f9 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f9);
    try {
      _jspx_th_i18n_005fi18ntag_005f9.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f9.setJspBody(new Helper( 9, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f9, null));
      _jspx_th_i18n_005fi18ntag_005f9.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f10 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f10);
    try {
      _jspx_th_i18n_005fi18ntag_005f10.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f10.setJspBody(new Helper( 10, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f10, null));
      _jspx_th_i18n_005fi18ntag_005f10.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f11 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f11);
    try {
      _jspx_th_i18n_005fi18ntag_005f11.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f11.setJspBody(new Helper( 11, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f11, null));
      _jspx_th_i18n_005fi18ntag_005f11.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f11);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f12 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f12);
    try {
      _jspx_th_i18n_005fi18ntag_005f12.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f12.setJspBody(new Helper( 12, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f12, null));
      _jspx_th_i18n_005fi18ntag_005f12.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f12);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f13 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f13);
    try {
      _jspx_th_i18n_005fi18ntag_005f13.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f13.setJspBody(new Helper( 13, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f13, null));
      _jspx_th_i18n_005fi18ntag_005f13.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f13);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f14 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f14);
    try {
      _jspx_th_i18n_005fi18ntag_005f14.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f14.setJspBody(new Helper( 14, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f14, null));
      _jspx_th_i18n_005fi18ntag_005f14.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f14);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f15 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f15);
    try {
      _jspx_th_i18n_005fi18ntag_005f15.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f15.setJspBody(new Helper( 15, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f15, null));
      _jspx_th_i18n_005fi18ntag_005f15.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f15);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f16 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f16);
    try {
      _jspx_th_i18n_005fi18ntag_005f16.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f16.setJspBody(new Helper( 16, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f16, null));
      _jspx_th_i18n_005fi18ntag_005f16.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f16);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f17 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f17);
    try {
      _jspx_th_i18n_005fi18ntag_005f17.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f17.setJspBody(new Helper( 17, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f17, null));
      _jspx_th_i18n_005fi18ntag_005f17.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f17);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f18 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f18);
    try {
      _jspx_th_i18n_005fi18ntag_005f18.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f18.setJspBody(new Helper( 18, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f18, null));
      _jspx_th_i18n_005fi18ntag_005f18.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f18);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f19 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f19);
    try {
      _jspx_th_i18n_005fi18ntag_005f19.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f19.setJspBody(new Helper( 19, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f19, null));
      _jspx_th_i18n_005fi18ntag_005f19.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f19);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f20 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f20);
    try {
      _jspx_th_i18n_005fi18ntag_005f20.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f20.setJspBody(new Helper( 20, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f20, null));
      _jspx_th_i18n_005fi18ntag_005f20.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f20);
    }
    return false;
  }

  private boolean _jspx_meth_i18n_005fi18ntag_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  i18n:i18ntag
    util.customTag.TagI18N _jspx_th_i18n_005fi18ntag_005f21 = new util.customTag.TagI18N();
    _jsp_getInstanceManager().newInstance(_jspx_th_i18n_005fi18ntag_005f21);
    try {
      _jspx_th_i18n_005fi18ntag_005f21.setJspContext(_jspx_page_context);
      _jspx_th_i18n_005fi18ntag_005f21.setJspBody(new Helper( 21, _jspx_page_context, _jspx_th_i18n_005fi18ntag_005f21, null));
      _jspx_th_i18n_005fi18ntag_005f21.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_i18n_005fi18ntag_005f21);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.homepage");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.products");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.order");
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.admin.admin");
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.admin.user");
      return false;
    }
    public boolean invoke5( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.admin.category");
      return false;
    }
    public boolean invoke6( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.provider");
      return false;
    }
    public boolean invoke7( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.admin.admin");
      return false;
    }
    public boolean invoke8( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.products");
      return false;
    }
    public boolean invoke9( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.menu.admin.category");
      return false;
    }
    public boolean invoke10( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable1.spcode");
      return false;
    }
    public boolean invoke11( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable1.TenSP");
      return false;
    }
    public boolean invoke12( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable1.sellPrice");
      return false;
    }
    public boolean invoke13( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable1.Discount");
      return false;
    }
    public boolean invoke14( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.caption");
      return false;
    }
    public boolean invoke15( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("form.action.add");
      return false;
    }
    public boolean invoke16( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("form.action.sort");
      return false;
    }
    public boolean invoke17( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("form.action.update");
      return false;
    }
    public boolean invoke18( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.copde");
      return false;
    }
    public boolean invoke19( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.name");
      return false;
    }
    public boolean invoke20( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.type");
      return false;
    }
    public boolean invoke21( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("index.proTable.provider");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
          case 5:
            invoke5( out );
            break;
          case 6:
            invoke6( out );
            break;
          case 7:
            invoke7( out );
            break;
          case 8:
            invoke8( out );
            break;
          case 9:
            invoke9( out );
            break;
          case 10:
            invoke10( out );
            break;
          case 11:
            invoke11( out );
            break;
          case 12:
            invoke12( out );
            break;
          case 13:
            invoke13( out );
            break;
          case 14:
            invoke14( out );
            break;
          case 15:
            invoke15( out );
            break;
          case 16:
            invoke16( out );
            break;
          case 17:
            invoke17( out );
            break;
          case 18:
            invoke18( out );
            break;
          case 19:
            invoke19( out );
            break;
          case 20:
            invoke20( out );
            break;
          case 21:
            invoke21( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
