/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-08-01 16:00:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Bài 02</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./bootstrap/bootstrap.min.css\">\r\n");
      out.write("	<!-- <script src=\"./jquery.min.js\"></script>  -->\r\n");
      out.write("	<script src=\"./bootstrap/jquery.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function loadPage(){\r\n");
      out.write("			//alert(\"Load site\");\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script>\r\n");
      out.write("		var masID = \"masLayer\";\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			$(\"#Cancel\").click(function() {\r\n");
      out.write("				//$(\"#productForm\").hide(500);\r\n");
      out.write("				//$(\"#productForm\").slideUp();\r\n");
      out.write("				$(\"#productForm\").fadeOut(500);\r\n");
      out.write("				var layer = document.getElementById(masID);\r\n");
      out.write("				document.body.removeChild(layer);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".addNew\").click(function() {\r\n");
      out.write("				//$(\"#productForm\").show(600);\r\n");
      out.write("				//$(\"#productForm\").toggle(600);\r\n");
      out.write("				//$(\"#productForm\").slideToggle();\r\n");
      out.write("				$(\"#productForm\").animate({left: '110px', top: '100px'});\r\n");
      out.write("				$(\"#productForm\").slideDown(500);\r\n");
      out.write("				$(\"#productForm\").css(\"z-index\", \"1000\");\r\n");
      out.write("				//$(\"#productForm\").fadeToggle(800);\r\n");
      out.write("				\r\n");
      out.write("				var layer = document.createElement(\"div\");\r\n");
      out.write("				layer.setAttribute(\"id\", masID);\r\n");
      out.write("				$(layer).css(\"position\", \"absolute\");\r\n");
      out.write("				$(layer).animate({left: '0px', top: '0px'});\r\n");
      out.write("				$(layer).css(\"width\", \"100%\");\r\n");
      out.write("				$(layer).css(\"height\", \"100%\");\r\n");
      out.write("				$(layer).css(\"background-color\", \"gray\");\r\n");
      out.write("				$(layer).css(\"z-index\", \"500\");\r\n");
      out.write("				$(layer).css(\"opacity\", \"0.25\");\r\n");
      out.write("				document.body.append(layer);\r\n");
      out.write("			});\r\n");
      out.write("			/*\r\n");
      out.write("			$(\"tr\").mouseenter(function() {\r\n");
      out.write("				$(this).css(\"background-color\", \"gray\");\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"tr\").mouseleave(function() {\r\n");
      out.write("				$(this).css(\"background-color\", \"white\");\r\n");
      out.write("			});\r\n");
      out.write("			*/\r\n");
      out.write("			\r\n");
      out.write("			// $(document).on(\"mouseenter\", \"tr\", function(){\r\n");
      out.write("				// $(this).css(\"background-color\", \"gray\");\r\n");
      out.write("				// $(this).addClass(\"selectedRow\");\r\n");
      out.write("			// });\r\n");
      out.write("			\r\n");
      out.write("			// $(document).on(\"mouseleave\", \"tr\", function(){\r\n");
      out.write("				// $(this).css(\"background-color\", \"white\");\r\n");
      out.write("				// $(this).removeClass(\"selectedRow\");\r\n");
      out.write("			// });\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.addNew {\r\n");
      out.write("			float: right;\r\n");
      out.write("			margin-right: 30px;\r\n");
      out.write("		}\r\n");
      out.write("		.selectedRow{\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	<style>\r\n");
      out.write("		td {\r\n");
      out.write("			padding-top: 2px;\r\n");
      out.write("			padding-left: 5px;\r\n");
      out.write("			text-align: top;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select, input {\r\n");
      out.write("			margin: 2px 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#proName {\r\n");
      out.write("			background-color: yellow;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.tdHead {\r\n");
      out.write("			color: blue;\r\n");
      out.write("			text-align: right;\r\n");
      out.write("			font-size: bold;\r\n");
      out.write("			padding-right: 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("		h1{\r\n");
      out.write("			color: blue;\r\n");
      out.write("			text-shadow: 2px 2px 5px lightblue;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		p {\r\n");
      out.write("			border: 1px solid black;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.p1 {\r\n");
      out.write("			color: DodgerBlue;\r\n");
      out.write("			border-left: 3px solid blue;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.p2 {\r\n");
      out.write("			color: MediumSeaGreen;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.p3{\r\n");
      out.write("			color: RGB(255,255,255);\r\n");
      out.write("			background-color: lightblue;\r\n");
      out.write("			padding: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.div01{\r\n");
      out.write("			background-image: url(\"../imgs/ICanNotUnderstandForYou.jpg\");\r\n");
      out.write("			background-repeat: no-repeat;\r\n");
      out.write("			color: white;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 500px;\r\n");
      out.write("			border: 1px double red;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.grid-container{\r\n");
      out.write("			display: grid;\r\n");
      out.write("			grid-template-areas: \r\n");
      out.write("				'lMenu lMenu lMenu lMenu header header header header header header header header'\r\n");
      out.write("				'lMenu lMenu lMenu lMenu content content content content content rMenu rMenu rMenu'\r\n");
      out.write("				'footer footer footer footer footer footer footer footer footer rMenu rMenu rMenu'\r\n");
      out.write("				'author author author author author author author author author author author author'\r\n");
      out.write("			;\r\n");
      out.write("			grid-gap: 5px;\r\n");
      out.write("			padding: 5px 10px 5px 5px;\r\n");
      out.write("			margin: 5px 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.grid-container > div {\r\n");
      out.write("			border: 1px solid blue;\r\n");
      out.write("			padding: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.header{\r\n");
      out.write("			grid-area: header;\r\n");
      out.write("			min-height: 100px;\r\n");
      out.write("			line-height: 100px;\r\n");
      out.write("			font-size: 28px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-weight: bolder;\r\n");
      out.write("			text-decoration: underline;\r\n");
      out.write("			text-transform: uppercase;\r\n");
      out.write("		}\r\n");
      out.write("		.leftMenu{grid-area: lMenu;}\r\n");
      out.write("		.content{grid-area: content;}\r\n");
      out.write("		.rightMenu{grid-area: rMenu;}\r\n");
      out.write("		.footer{grid-area: footer;}\r\n");
      out.write("		.author{grid-area: author;}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onload=\"loadPage()\">\r\n");
      out.write("	<div class=\"grid-container\">\r\n");
      out.write("		<div class=\"header\">Site Header</div>\r\n");
      out.write("		<div class=\"leftMenu\">Left Menu</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<div id=\"productForm\" style=\"display: none; border: 1px solid blue; padding: 5px; width: 40%; min-width:640px;position: absolute; background-color: white;\">\r\n");
      out.write("			\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "home.jsp", out, false);
      out.write("  \r\n");
      out.write("\r\n");
      out.write("		 	<button id=\"Cancel\">Close</button>	\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div style=\"width: 100%; float: right;\">\r\n");
      out.write("				<table border=\"1\" style=\"width: 100%;border-collapse: collapse; \" id=\"proList\">\r\n");
      out.write("					<caption>\r\n");
      out.write("						Danh sách sản phẩm <button class=\"addNew\">Thêm mới sản phẩm</button>\r\n");
      out.write("					</caption>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Mã sản phẩm</th>\r\n");
      out.write("						<th>Tên sản phẩm</th>\r\n");
      out.write("						<th>Giá nhập về</th>\r\n");
      out.write("						<th>Giá bán ra</th>\r\n");
      out.write("						<th>#</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"rightMenu\">Right Menu</div>\r\n");
      out.write("		<div class=\"footer\">Footer</div>\r\n");
      out.write("		<div class=\"author\">Tac Gia</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		var inputTexts = document.getElementsByTagName(\"input\");\r\n");
      out.write("		for(i = 0; i < inputTexts.length; i ++){\r\n");
      out.write("			if(inputTexts[i].getAttribute(\"type\") == \"text\" || inputTexts[i].getAttribute(\"type\") == \"password\"){\r\n");
      out.write("				inputTexts[i].setAttribute(\"onfocus\", \"changeBackgroudYellow(this)\");\r\n");
      out.write("				inputTexts[i].setAttribute(\"onblur\", \"changeBackgroudWhite(this)\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function validateData(){\r\n");
      out.write("			// xac nhan cac truong not-null\r\n");
      out.write("			code = document.getElementById(\"proCode\").value;\r\n");
      out.write("			name = document.getElementById(\"proName\").value;\r\n");
      out.write("			if(code == null || code == \"\") {\r\n");
      out.write("				alert(\"Mã sản phẩm không được bỏ trống\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(name == null || name == \"\") {\r\n");
      out.write("				alert(\"Tên sản phẩm không được bỏ trống\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// phai la kieu so\r\n");
      out.write("			try{\r\n");
      out.write("				cost = parseInt(document.getElementById(\"proCost\").value);\r\n");
      out.write("				price = parseInt(document.getElementById(\"proPri\").value);\r\n");
      out.write("				if(isNaN(cost) || isNaN(price)){\r\n");
      out.write("					alert(\"Giá trị nhập vào cho 'Giá nhập về' hoặc 'Giá bán ra' không hợp lệ\");\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("			}catch(err){\r\n");
      out.write("				alert(err + \"\\t-> Giá trị nhập vào cho 'Giá nhập về' hoặc 'Giá bán ra' không hợp lệ\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// rang buoc du lieu: GiaBanRa > GiaNhapVe\r\n");
      out.write("			if(cost > price) {\r\n");
      out.write("				alert(\"Giá bán ra phải lớn hơn giá nhập về\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			return true;\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		function changeProCode(element){\r\n");
      out.write("			element.value = element.value.toUpperCase();\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		function changeBackgroudYellow(element){\r\n");
      out.write("			element.style.background=\"yellow\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function changeBackgroudWhite(element){\r\n");
      out.write("			element.style.background=\"white\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var proTypes = [\"Smart Phone\", \"Tablet\", \"Laptop\", \"Máy bàn\", \"Máy in\", \"Test\"];\r\n");
      out.write("		proTypes.sort();\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var proTypElement = document.getElementById(\"proType\");\r\n");
      out.write("		\r\n");
      out.write("		for(i = 0; i < proTypes.length; i ++){\r\n");
      out.write("			optElement = document.createElement(\"option\");\r\n");
      out.write("			textElement = document.createTextNode(proTypes[i]);\r\n");
      out.write("			\r\n");
      out.write("			optElement.setAttribute(\"value\", (i + 1));\r\n");
      out.write("			optElement.appendChild(textElement);\r\n");
      out.write("			\r\n");
      out.write("			proTypElement.appendChild(optElement);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function deleteRow(rowId){\r\n");
      out.write("			var proTable = document.getElementById(\"proList\");\r\n");
      out.write("			var trEle = document.getElementById(rowId);\r\n");
      out.write("			proTable.removeChild(trEle);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function saveProduct(){\r\n");
      out.write("			if(validateData()){\r\n");
      out.write("				var proTable = document.getElementById(\"proList\");\r\n");
      out.write("				var trEle = document.createElement(\"tr\");\r\n");
      out.write("				var trId = \"tr_\" + document.getElementById(\"proCode\").value;\r\n");
      out.write("				trEle.setAttribute(\"id\", trId);\r\n");
      out.write("				\r\n");
      out.write("				var tdProCode = document.createElement(\"td\");\r\n");
      out.write("				var tdProName = document.createElement(\"td\");\r\n");
      out.write("				var tdProCost = document.createElement(\"td\");\r\n");
      out.write("				var tdProPri  = document.createElement(\"td\");\r\n");
      out.write("				var tdAction  = document.createElement(\"td\");\r\n");
      out.write("				\r\n");
      out.write("				var btEle = document.createElement(\"BUTTON\");\r\n");
      out.write("				btEle.appendChild(document.createTextNode(\"Delete\"));\r\n");
      out.write("				btEle.setAttribute(\"onclick\", \"deleteRow('\"+trId+\"')\");\r\n");
      out.write("				\r\n");
      out.write("				tdProCode.appendChild(document.createTextNode(document.getElementById(\"proCode\").value));\r\n");
      out.write("				tdProName.appendChild(document.createTextNode(document.getElementById(\"proName\").value));\r\n");
      out.write("				tdProCost.appendChild(document.createTextNode(document.getElementById(\"proCost\").value));\r\n");
      out.write("				tdProPri.appendChild(document.createTextNode(document.getElementById(\"proPri\").value));\r\n");
      out.write("				tdAction.appendChild(btEle);\r\n");
      out.write("				\r\n");
      out.write("				trEle.appendChild(tdProCode);\r\n");
      out.write("				trEle.appendChild(tdProName);\r\n");
      out.write("				trEle.appendChild(tdProCost);\r\n");
      out.write("				trEle.appendChild(tdProPri);\r\n");
      out.write("				trEle.appendChild(tdAction);\r\n");
      out.write("				\r\n");
      out.write("				proTable.appendChild(trEle);\r\n");
      out.write("				\r\n");
      out.write("				var layer = document.getElementById(masID);\r\n");
      out.write("				document.body.removeChild(layer);\r\n");
      out.write("				var productForm = document.getElementById(\"productForm\");\r\n");
      out.write("				productForm.style.display = \"none\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
